# Generated by Django 4.2.1 on 2023-06-01 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRangeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('startAge', models.IntegerField()),
                ('endAge', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttributesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('icon', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompaniesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('qualifications', models.TextField()),
                ('jobIcon', models.FilePathField()),
                ('deadline', models.DateTimeField()),
                ('link', models.URLField()),
                ('isOpen', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.BinaryField(max_length=500, null=True)),
                ('phonenumber', models.CharField(max_length=50, null=True)),
                ('companyName', models.CharField(max_length=100, null=True)),
                ('employId', models.CharField(max_length=100, null=True)),
                ('linkedin', models.CharField(max_length=200, null=True)),
                ('github', models.CharField(max_length=200, null=True)),
                ('leetcode', models.CharField(max_length=200, null=True)),
                ('headshot', models.FilePathField(null=True)),
                ('resume', models.FilePathField(null=True)),
                ('ageRangeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.agerangemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('skillId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.skillsmodel')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.usermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='usermodel',
            name='userTypeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.usertypemodel'),
        ),
        migrations.CreateModel(
            name='UserCompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.companiesmodel')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.usermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UrlContentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('url', models.URLField()),
                ('skillId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.skillsmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentAttributeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('receivedDate', models.DateTimeField()),
                ('attributeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.attributesmodel')),
                ('receivedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_attribute_id', to='mainapp.usermodel')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attribute_id', to='mainapp.usermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LInkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('url', models.URLField()),
                ('time', models.IntegerField()),
                ('lastVisitDate', models.DateTimeField()),
                ('frequency', models.FloatField()),
                ('clickCount', models.IntegerField()),
                ('level', models.IntegerField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.usermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobProcessingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.IntegerField()),
                ('interviewDateTime', models.DateTimeField(null=True)),
                ('acceptDateTime', models.DateTimeField(null=True)),
                ('rejectDateTime', models.DateTimeField(null=True)),
                ('jobId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.jobmodel')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.usermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='recruiterId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.usermodel'),
        ),
        migrations.CreateModel(
            name='ConnectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('messages', models.JSONField()),
                ('recruiterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_user_id', to='mainapp.usermodel')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_user_id', to='mainapp.usermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
