# Generated by Django 4.2.1 on 2023-06-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_usermodel_agerangeid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
