# Generated by Django 4.2.1 on 2023-06-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_usermodel_agerangeid_usermodel_companyname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='headshot',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='resume',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
