# Generated by Django 4.2.1 on 2023-06-03 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_agerangemodel_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupationModel',
            fields=[
                ('occupationId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('descrioption', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='skillsmodel',
            name='hot_technology',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='skillsmodel',
            name='in_demand',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='skillsmodel',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name='skillsmodel',
            name='occupationId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.occupationmodel'),
        ),
    ]
