# Generated by Django 4.2.1 on 2023-06-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_occupationmodel_skillsmodel_hot_technology_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occupationmodel',
            old_name='descrioption',
            new_name='description',
        ),
    ]
