# Generated by Django 4.2.1 on 2023-06-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_rename_descrioption_occupationmodel_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkmodel',
            old_name='lastVisitDate',
            new_name='lastVisitDateTime',
        ),
        migrations.AlterField(
            model_name='linkmodel',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
